# Generated by Django 4.0.4 on 2022-05-02 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_transformer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint_transformer',
            name='complaint_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
