# Generated by Django 4.0.4 on 2022-05-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Customer Complaints', 'Customer Complaints'), ('Section Initiated Complaints', 'Section Initiated Complaints')], default='Customer Complaints', max_length=30, null=True),
        ),
    ]
