# Generated by Django 4.0.4 on 2022-06-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_complaint_type_and_more'),
        ('complaints', '0014_alter_complaint_user_and_more'),
    ]

    operations = [
    ]
