# Generated by Django 4.0.4 on 2022-06-12 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_merge_20220613_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Customer Complaints', 'Customer Complaints'), ('Section Initiated Complaints', 'Section Initiated Complaints')], default='Customer Complaints', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complaint_transformer',
            name='complaint_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint_transformer',
            name='complaint_trans',
            field=models.CharField(choices=[('Transformer 1', 'Transformer 1'), ('Transformer 2', 'Transformer 2'), ('Transformer 3', 'Transformer 3'), ('Transformer 4', 'Transformer 4'), ('Transformer 5', 'Transformer 5'), ('Transformer 6', 'Transformer 6'), ('Transformer 7', 'Transformer 7')], default='Transformer 1', max_length=20, null=True),
        ),
    ]
